companies:
  - name: "スポーツフィールド"
    ticker: "7080"
    ir_url: "https://sports-f.co.jp/ir/"
  - name: "グランディハウス"
    ticker: "8999"
    ir_url: "https://www.grandy.co.jp/ir/"
  - name: "クオルテック"
    ticker: "9165"
    ir_url: "https://www.qualtec.co.jp/irsite/"
  - name: "塩水港精糖"
    ticker: "2112"
    ir_url: "https://www.ensuiko.co.jp/ir/"
  - name: "ディー・エヌ・エー"
    ticker: "2432"
    ir_url: "https://dena.com/jp/ir/irnews.html"
  - name: "Ｐｈｏｔｏｓｙｎｔｈ"
    ticker: "4379"
    ir_url: "https://photosynth.co.jp/ir"
  - name: "ギフトホールディングス"
    ticker: "9279"
    ir_url: "https://www.gift-group.co.jp/ir"
    